# Generated by Django 3.2.16 on 2023-11-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20231104_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'verbose_name': 'сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
